#!/bin/bash

# only uncomment on first go, otherwise everything is lost!!!
# echo "n_games; ml_alg; keys; scaler; accuracy; pr_auc; roc_auc; time_consumption; params" > output/past_n_games.csv

for n in $(seq 4 50)
do
  for scaler in MinMax Standard
  do
    echo "Start on run number $n with scaler $scaler"
    python main_past_n_games.py $n $scaler > /tmp/auslauf.txt # uncomment redirection if output is desired
  done
done
